### ISSUE TITLE
コメント間違い

### ISSUE THREAD

**Issue by Hayato0802** [doy1022/ConvertTool#5]
![image](https://github.com/doy1022/ConvertTool/assets/76469558/727335bd-b055-4961-b231-f28ab4dabc3a)

**Comment by doy1022** [comment]
修正完了しました（念のためremoveFOFromHeaderもキャプチャに映しておきます）
![image](https://github.com/doy1022/ConvertTool/assets/169744462/fa10e7f5-f28d-4bad-810e-e88b3cf523a7)
